"""Добавление поля под id_vk

Revision ID: 521c6acb8a3e
Revises: 746f47746e5d
Create Date: 2025-04-04 13:42:28.594274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521c6acb8a3e'
down_revision: Union[str, None] = '746f47746e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('vk_item_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'vk_item_id')
    # ### end Alembic commands ###
