"""Добавление поля под id_vk

Revision ID: 746f47746e5d
Revises: 46476f65cf76
Create Date: 2025-04-03 06:02:49.620544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746f47746e5d'
down_revision: Union[str, None] = '46476f65cf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('tg_picture_id', sa.String(), nullable=True))
    op.add_column('goods', sa.Column('vk_picture_id', sa.Integer(), nullable=True))
    op.drop_column('goods', 'picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('goods', 'vk_picture_id')
    op.drop_column('goods', 'tg_picture_id')
    # ### end Alembic commands ###
