"""Initial revision

Revision ID: 8587dbf10d64
Revises: cc01417d5f77
Create Date: 2025-03-26 16:32:16.486568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8587dbf10d64'
down_revision: Union[str, None] = 'cc01417d5f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'offerID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goods', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goods', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goods', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goods', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('goods', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('goods', 'offerID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
